version: '3'

services:
  app:
    build: .
    image: ${DOCKER_USER_ID}/flask
    command: python main.py
  production:
    image: ${DOCKER_USER_ID}/flask:${BUILD_NUMBER}
    volumes:
      - .:/code

    ports:
      - "8888:8888"